### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by MsLolita** [dmytrostriletskyi/threads-net#46]
when I log in, it throws the current error. If I'm not mistaken, the developers changed the API a little.

```
from threadspy import ThreadsAPI

api = ThreadsAPI(username="username", password="password")
```

```

Traceback (most recent call last):
  File "D:\user\prog\threads_bot\v1\tests\test.py", line 2, in <module>
    threads = Threads(username='username', password='password')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\user\prog\threads_bot\v1\venv\Lib\site-packages\threads\main.py", line 27, in __init__
    self.private_api = PrivateThreadsApi(username=username, password=password)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\user\prog\threads_bot\v1\venv\Lib\site-packages\threads\apis\private.py", line 51, in __init__
    self.user_id = self.get_user_id(username=username)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\user\prog\threads_bot\v1\venv\Lib\site-packages\threads\apis\private.py", line 67, in get_user_id
    user_id_as_string = response.json().get('user').get('pk')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by dmytrostriletskyi** [comment]
Hi, @MsLolita! 👋

Yeah, I made a little research and found that the problem is in the API, so we need to adjust the code. I have also checked a few more libraries on other languages (`JavaScript`) and found that they have the same issue, so it is likely API.

**Comment by vforv** [comment]
Same issue here, look like some issue with response handling

**Comment by dmytrostriletskyi** [comment]
>Same issue here, look like some issue with response handling

No, response itself tells that `login` was performed properly (below is the response text):

```
{"layout":{"bloks_payload":{"data":[],"props":[{"id":"-6917714003244327204","name":"ttrc_instance_id"},{"id":"2231046902902521263","name":"override_login_success_action"}],"error_attribution":{"logging_id":"{\"callsite\":\"{\\\"product\\\":\\\"bloks_caa_login\\\",\\\"feature\\\":\\\"com.bloks.www.bloks.caa.login.async.send_login_request\\\",\\\"integration\\\":\\\"bloks_screen\\\",\\\"oncall\\\":\\\"caa_login\\\"}\",\"push_phase\":\"C3\",\"version\":1,\"request_id\":\"AuAZHWTpaWclJmdZTF_nf2Z\"}"},"tree":{"㐟":{"#":" (bk.action.core.TakeLast, (ig.action.cdsdialog.OpenDialog, (bk.action.tree.Make, (bk.action.i32.Const, 13799), (bk.action.i32.Const, 40), \"Unable to log in\", (bk.action.i32.Const, 35), \"An unexpected error occurred. Please try logging in again.\", (bk.action.i32.Const, 36), (bk.action.tree.Make, (bk.action.i32.Const, 13800), (bk.action.i32.Const, 36), \"OK\", (bk.action.i32.Const, 35), (bk.action.core.FuncConst, (bk.action.logging.LogEvent, \"caa_login_client_events_ig\", \"\", (bk.action.map.Make, (bk.action.array.Make, \"core\", \"login_params\"), (bk.action.array.Make, (bk.action.map.Make, (bk.action.array.Make, \"event\", \"event_category\", \"event_flow\", \"event_request_id\", \"event_step\", \"is_dark_mode\", \"exception_code\", \"exception_message\", \"exception_type\", \"extra_client_data\", \"logged_out_identifier\", \"logged_in_identifier\", \"waterfall_id\"), (bk.action.array.Make, \"login_error_dialog_ok_clicked\", \"login_home_page_interaction\", \"login_manual\", \"8dd9a09a-ee89-4189-a5e6-75d049926ac5\", \"home_page\", (ig.action.IsDarkModeEnabled), (bk.action.i32.Const, 0), \"\", \"\", (bk.action.map.Make, (bk.action.array.Make), (bk.action.array.Make)), \"\", \"\", \"29888ff7-0346-4acf-aebe-c26ae3c5c184\")), (bk.action.map.Make, (bk.action.array.Make), (bk.action.array.Make))))))), (bk.action.i32.Const, 42), (bk.action.i32.Const, 0)), (bk.action.tree.Make, (bk.action.i32.Const, 13808))), (bk.action.map.Make, (bk.action.array.Make, \"should_dismiss_loading\"), (bk.action.array.Make, (bk.action.bool.Const, true))))"}}}},"status":"ok"}{"layout":{"bloks_payload":{"data":[],"props":[{"id":"-6917714003244327204","name":"ttrc_instance_id"},{"id":"2231046902902521263","name":"override_login_success_action"}],"error_attribution":{"logging_id":"{\"callsite\":\"{\\\"product\\\":\\\"bloks_caa_login\\\",\\\"feature\\\":\\\"com.bloks.www.bloks.caa.login.async.send_login_request\\\",\\\"integration\\\":\\\"bloks_screen\\\",\\\"oncall\\\":\\\"caa_login\\\"}\",\"push_phase\":\"C3\",\"version\":1,\"request_id\":\"A7qO-aAvJbTs6GpzwxJXaLE\"}"},"tree":{"㐟":{"#":" (bk.action.core.TakeLast, (ig.action.cdsdialog.OpenDialog, (bk.action.tree.Make, (bk.action.i32.Const, 13799), (bk.action.i32.Const, 40), \"Unable to log in\", (bk.action.i32.Const, 35), \"An unexpected error occurred. Please try logging in again.\", (bk.action.i32.Const, 36), (bk.action.tree.Make, (bk.action.i32.Const, 13800), (bk.action.i32.Const, 36), \"OK\", (bk.action.i32.Const, 35), (bk.action.core.FuncConst, (bk.action.logging.LogEvent, \"caa_login_client_events_ig\", \"\", (bk.action.map.Make, (bk.action.array.Make, \"core\", \"login_params\"), (bk.action.array.Make, (bk.action.map.Make, (bk.action.array.Make, \"event\", \"event_category\", \"event_flow\", \"event_request_id\", \"event_step\", \"is_dark_mode\", \"exception_code\", \"exception_message\", \"exception_type\", \"extra_client_data\", \"logged_out_identifier\", \"logged_in_identifier\", \"waterfall_id\"), (bk.action.array.Make, \"login_error_dialog_ok_clicked\", \"login_home_page_interaction\", \"login_manual\", \"cbba4288-4fe2-4194-ae53-ef8e04ebee58\", \"home_page\", (ig.action.IsDarkModeEnabled), (bk.action.i32.Const, 0), \"\", \"\", (bk.action.map.Make, (bk.action.array.Make), (bk.action.array.Make)), \"\", \"\", \"5d4b9241-f25f-40ab-b5fa-5e84e6f1b2e5\")), (bk.action.map.Make, (bk.action.array.Make), (bk.action.array.Make))))))), (bk.action.i32.Const, 42), (bk.action.i32.Const, 0)), (bk.action.tree.Make, (bk.action.i32.Const, 13808))), (bk.action.map.Make, (bk.action.array.Make, \"should_dismiss_loading\"), (bk.action.array.Make, (bk.action.bool.Const, true))))"}}}},"status":"ok"}
```

> Unable to log in
> login_error_dialog_ok_clicked

**Comment by vforv** [comment]
Aha I see thank you for response and good work

**Comment by vforv** [comment]
@dmytrostriletskyi I just tried login into Instagram account but it not allow, look like our accounts get blocked or something

**Comment by vforv** [comment]
Ok I can now login again

Any solution for this?

**Comment by MsLolita** [comment]
> Ok I can now login again
> 
> Any solution for this?

https://github.com/Danie1/threads-api/issues/16

**Comment by dmytrostriletskyi** [comment]
I will dive into fix tomorrow, did not have any time today.

> https://github.com/Danie1/threads-api/issues/16

Thanks for the info, but I would try to avoid using any other 3rd-party for now. Let's see how it will end up, maybe it would be easier to integrate it as well. But let me try to fix it, fixing the existing codebase.

**Comment by dmytrostriletskyi** [comment]
Seems I managed to fix it, prepering a PR.

**Comment by dmytrostriletskyi** [comment]
Should be fixed, use latest release — https://github.com/dmytrostriletskyi/threads-net/releases/tag/v0.0.35

BTW, you can check how fix the done and what insights I gained — https://github.com/dmytrostriletskyi/threads-net/pull/50

**Comment by evandroamparo** [comment]
I still see the same error:

Traceback (most recent call last):
  File "/workspaces/threads-net/examples/private/get_user.py", line 16, in <module>
    user_id = threads.private_api.get_user_id(username='zuck')
  File "/home/codespace/.local/lib/python3.10/site-packages/threads_net-0.0.32-py3.10.egg/threads/apis/private.py", line 65, in get_user_id
AttributeError: 'PrivateThreadsApi' object has no attribute 'headers'

**Comment by dmytrostriletskyi** [comment]
@evandroamparo, can you specify the xredentials directly into the files? I assume .env does not work for the libraru currently.

**Comment by dmytrostriletskyi** [comment]
Please, if it does not work for you still, open the separate issue.
